// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/token.proto

package token

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Token service

func NewTokenEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Token service

type TokenService interface {
	GetTokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...client.CallOption) (*TokenInfoResponse, error)
}

type tokenService struct {
	c    client.Client
	name string
}

func NewTokenService(name string, c client.Client) TokenService {
	return &tokenService{
		c:    c,
		name: name,
	}
}

func (c *tokenService) GetTokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...client.CallOption) (*TokenInfoResponse, error) {
	req := c.c.NewRequest(c.name, "Token.GetTokenInfo", in)
	out := new(TokenInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Token service

type TokenHandler interface {
	GetTokenInfo(context.Context, *TokenInfoRequest, *TokenInfoResponse) error
}

func RegisterTokenHandler(s server.Server, hdlr TokenHandler, opts ...server.HandlerOption) error {
	type token interface {
		GetTokenInfo(ctx context.Context, in *TokenInfoRequest, out *TokenInfoResponse) error
	}
	type Token struct {
		token
	}
	h := &tokenHandler{hdlr}
	return s.Handle(s.NewHandler(&Token{h}, opts...))
}

type tokenHandler struct {
	TokenHandler
}

func (h *tokenHandler) GetTokenInfo(ctx context.Context, in *TokenInfoRequest, out *TokenInfoResponse) error {
	return h.TokenHandler.GetTokenInfo(ctx, in, out)
}
