// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/information.proto

package information

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/structpb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Information service

func NewInformationEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Information service

type InformationService interface {
	TransactionInformation(ctx context.Context, in *TransactionInformationRequest, opts ...client.CallOption) (*TransactionInformationResponse, error)
}

type informationService struct {
	c    client.Client
	name string
}

func NewInformationService(name string, c client.Client) InformationService {
	return &informationService{
		c:    c,
		name: name,
	}
}

func (c *informationService) TransactionInformation(ctx context.Context, in *TransactionInformationRequest, opts ...client.CallOption) (*TransactionInformationResponse, error) {
	req := c.c.NewRequest(c.name, "Information.TransactionInformation", in)
	out := new(TransactionInformationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Information service

type InformationHandler interface {
	TransactionInformation(context.Context, *TransactionInformationRequest, *TransactionInformationResponse) error
}

func RegisterInformationHandler(s server.Server, hdlr InformationHandler, opts ...server.HandlerOption) error {
	type information interface {
		TransactionInformation(ctx context.Context, in *TransactionInformationRequest, out *TransactionInformationResponse) error
	}
	type Information struct {
		information
	}
	h := &informationHandler{hdlr}
	return s.Handle(s.NewHandler(&Information{h}, opts...))
}

type informationHandler struct {
	InformationHandler
}

func (h *informationHandler) TransactionInformation(ctx context.Context, in *TransactionInformationRequest, out *TransactionInformationResponse) error {
	return h.InformationHandler.TransactionInformation(ctx, in, out)
}
