// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/transactions.proto

package transactions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Transactions service

func NewTransactionsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Transactions service

type TransactionsService interface {
	SingleTransaction(ctx context.Context, in *SingleTransactionRequest, opts ...client.CallOption) (*SingleTransactionResponse, error)
	AllTransactions(ctx context.Context, in *AllTransactionsRequest, opts ...client.CallOption) (*AllTransactionsResponse, error)
	TransactionLogs(ctx context.Context, in *TransactionLogsRequest, opts ...client.CallOption) (*TransactionLogsResponse, error)
}

type transactionsService struct {
	c    client.Client
	name string
}

func NewTransactionsService(name string, c client.Client) TransactionsService {
	return &transactionsService{
		c:    c,
		name: name,
	}
}

func (c *transactionsService) SingleTransaction(ctx context.Context, in *SingleTransactionRequest, opts ...client.CallOption) (*SingleTransactionResponse, error) {
	req := c.c.NewRequest(c.name, "Transactions.SingleTransaction", in)
	out := new(SingleTransactionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsService) AllTransactions(ctx context.Context, in *AllTransactionsRequest, opts ...client.CallOption) (*AllTransactionsResponse, error) {
	req := c.c.NewRequest(c.name, "Transactions.AllTransactions", in)
	out := new(AllTransactionsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsService) TransactionLogs(ctx context.Context, in *TransactionLogsRequest, opts ...client.CallOption) (*TransactionLogsResponse, error) {
	req := c.c.NewRequest(c.name, "Transactions.TransactionLogs", in)
	out := new(TransactionLogsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Transactions service

type TransactionsHandler interface {
	SingleTransaction(context.Context, *SingleTransactionRequest, *SingleTransactionResponse) error
	AllTransactions(context.Context, *AllTransactionsRequest, *AllTransactionsResponse) error
	TransactionLogs(context.Context, *TransactionLogsRequest, *TransactionLogsResponse) error
}

func RegisterTransactionsHandler(s server.Server, hdlr TransactionsHandler, opts ...server.HandlerOption) error {
	type transactions interface {
		SingleTransaction(ctx context.Context, in *SingleTransactionRequest, out *SingleTransactionResponse) error
		AllTransactions(ctx context.Context, in *AllTransactionsRequest, out *AllTransactionsResponse) error
		TransactionLogs(ctx context.Context, in *TransactionLogsRequest, out *TransactionLogsResponse) error
	}
	type Transactions struct {
		transactions
	}
	h := &transactionsHandler{hdlr}
	return s.Handle(s.NewHandler(&Transactions{h}, opts...))
}

type transactionsHandler struct {
	TransactionsHandler
}

func (h *transactionsHandler) SingleTransaction(ctx context.Context, in *SingleTransactionRequest, out *SingleTransactionResponse) error {
	return h.TransactionsHandler.SingleTransaction(ctx, in, out)
}

func (h *transactionsHandler) AllTransactions(ctx context.Context, in *AllTransactionsRequest, out *AllTransactionsResponse) error {
	return h.TransactionsHandler.AllTransactions(ctx, in, out)
}

func (h *transactionsHandler) TransactionLogs(ctx context.Context, in *TransactionLogsRequest, out *TransactionLogsResponse) error {
	return h.TransactionsHandler.TransactionLogs(ctx, in, out)
}
